version: 2

jobs:
  build:
    docker:
      - image: ros:kinetic-robot-xenial
    steps:
      - checkout
      - run: apt-get update && apt-get install -y ros-kinetic-ros-base
      - run: source /opt/ros/kinetic/setup.bash && catkin_make
   
    branches:
        ignore:
          - master
