version: 2

jobs:
  build:
    docker:
      - image: ros:kinetic-robot-xenial
      - image: cibuilds/github:0.10
    steps:
      - checkout
#      - run: apt-get update && apt-get install -y ros-kinetic-desktop-full
#      - run: source /opt/ros/kinetic/setup.bash && catkin_make
      - run: echo "hello world" # run the `echo` command
      - run: pwd && ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} v0.0.0
